### ISSUE TITLE
App crashes when going through the setup wizard

### ISSUE THREAD

**Issue by palmercluff** [net-angel/netangel-protection-android#41]
On the 3rd slide (Device Administrator), when clicking on the 'Prevent Uninstall' button then clicking 'Activate', it crashed the App. But when I went back to the App it resumed on the slide I was on, and I was able to get to the 4th and final slide. When I attempted to re-create the same scenario on my phone, it worked fine though.

I am using an LG Volt 2 with Android version 5.1.1

On my wife's phone, on that same 3rd slide, then pressing 'Activate' to prevent uninstall, it gave her this error (image below), but after she hit OK it took her back to 3rd slide no problem. When uninstalling and re-installing the app to re-create the same scenerio, it happens every time. Always an 'Unfortunately, NetAngel Protection has stopped' 

She has a LG Tribute HD with Android version 6.0.1. The image below is what shows up when she clicks 'Activate'

Another thing to mention is to continue onto the 4th slide, one must click on 'Prevent Uninstall' again even after activating under the Android system settings.

![image](https://cloud.githubusercontent.com/assets/10787452/23772479/55bd8d62-04d8-11e7-91f2-afa8d9d1949b.png)

**Comment by eterry1388** [comment]
Did you report it?  I added another issue of a crash that was reported.  See issue #44

**Comment by eterry1388** [comment]
I you didn't report it, please do so we can see the backtrace.

**Comment by palmercluff** [comment]
Ah I see. All these years of never hitting 'report' has become a bad habit. I'll have my wife re-create the issue and report it.

**Comment by palmercluff** [comment]
The feedback was sent. Let me know if you didn't get it.

**Comment by eterry1388** [comment]
```
java.lang.RuntimeException: Unable to start receiver com.netangel.netangelprotection.receiver.DeviceAdminRequestReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2784)
	at android.app.ActivityThread.access$1800(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5585)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:672)
	at android.app.ContextImpl.startActivity(ContextImpl.java:659)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
	at com.netangel.netangelprotection.ui.OnboardingActivity.start(OnboardingActivity.java:43)
	at com.netangel.netangelprotection.receiver.DeviceAdminRequestReceiver.startOnBoardingActivity(DeviceAdminRequestReceiver.java:54)
	at com.netangel.netangelprotection.receiver.DeviceAdminRequestReceiver.onEnabled(DeviceAdminRequestReceiver.java:30)
	at android.app.admin.DeviceAdminReceiver.onReceive(DeviceAdminReceiver.java:528)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2773)
	... 8 more
```

**Comment by klinker24** [comment]
Ahh an easy fix, some devices need this, some don't, will fix it now

**Comment by eterry1388** [comment]
@palmercluff Can you test this on the device that was having this issue?  I'd like to know if the latest version of the app fixes this issue. You probably have to uninstall the app, then reinstall it fresh to go through the wizard again.  If it is fixed, you can close this issue.

**Comment by palmercluff** [comment]
Yeah I will get to it later this afternoon.

**Comment by palmercluff** [comment]
The error showed up after clicking on "connect to netangel" on the last slide. I sent the error report.

**Comment by klinker24** [comment]
The fix for that should be here: https://github.com/net-angel/netangel-protection-android/pull/51

It hasn't been merged yet
