### ISSUE TITLE
App Crash - ActivityNotFoundException

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#44]
**Device:** LG X power (mk6p55)
**User message:** System keeps crashing when i try to sign up
**Last reported:** Mar 7, 7:27 AM
**Android version:** Android 6.0

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://dashboard.netangel.com/... }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
	at android.app.Activity.startActivityForResult(Activity.java:3958)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:3919)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at android.app.Activity.startActivity(Activity.java:4242)
	at android.app.Activity.startActivity(Activity.java:4210)
	at com.netangel.netangelprotection.ui.LoginActivity.onClickSignUp(LoginActivity.java:135)
	at com.netangel.netangelprotection.ui.LoginActivity$$ViewBinder$InnerUnbinder$1.doClick(LoginActivity$$ViewBinder.java:39)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
	at android.view.View.performClick(View.java:5217)
	at android.view.View$PerformClick.run(View.java:21349)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5585)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by klinker24** [comment]
This is failing to find your an app to open a web link, did you disable chrome or something? I can put a try/catch around that, but it is the system that recieved that action, not NetAngel, so there isn't much for a workaround

**Comment by eterry1388** [comment]
This wasn't me.  It was reported by some random user.  So I can't answer for whether Chrome was disabled or not.

**Comment by klinker24** [comment]
So I can do one of two things:

1.) catch the `Exception` and just tell the user they have to go to it from their computer
2.) Implement an in-app browser through Android's `WebView`.

The first is extremely simple, of course, the second one may take an hour or so to implement, but is also very simple. I would probably prefer the 2nd option, if I were a user

**Comment by klinker24** [comment]
I went ahead with the second option. Should provide a much better experience than the first
