### ISSUE TITLE
App Crash - IllegalStateException: Activity has been destroyed

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#48]
```
java.lang.IllegalStateException: Activity has been destroyed
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1864)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:649)
	at android.support.v4.app.BackStackRecord.commitAllowingStateLoss(BackStackRecord.java:614)
	at com.netangel.netangelprotection.ui.WaitingDialog.show(WaitingDialog.java:20)
	at com.netangel.netangelprotection.ui.OnboardingActivity.updateState(OnboardingActivity.java:175)
	at com.netangel.netangelprotection.ui.OnboardingActivity.access$000(OnboardingActivity.java:28)
	at com.netangel.netangelprotection.ui.OnboardingActivity$3.run(OnboardingActivity.java:168)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by eterry1388** [comment]
So far, 7 people have reported this couple days.
